//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketStokOtomasyonu.MarketStokWebServis {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MarketStokWebServis.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUrunler", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getUrunler();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUrunler", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getUrunlerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStokBiten", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getStokBiten();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStokBiten", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getStokBitenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStokAzalan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getStokAzalan();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getStokAzalan", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getStokAzalanAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getKategori", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getKategori();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getKategori", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getKategoriAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postUrunSil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet postUrunSil(string barkod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postUrunSil", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> postUrunSilAsync(string barkod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postUrun", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet postUrun(string urun_barkod, int kategori_id, string urun_adi, int miktar, string fiyat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postUrun", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> postUrunAsync(string urun_barkod, int kategori_id, string urun_adi, int miktar, string fiyat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postUrunGuncelle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet postUrunGuncelle(string urun_barkod, int kategori_id, string urun_adi, int miktar, string fiyat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postUrunGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> postUrunGuncelleAsync(string urun_barkod, int kategori_id, string urun_adi, int miktar, string fiyat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getArama", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getArama(string barkod, string urun_adi, string kategori_adi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getArama", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAramaAsync(string barkod, string urun_adi, string kategori_adi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SorguCalistir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SorguCalistir(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SorguCalistir", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> SorguCalistirAsync(string query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTedarikciler", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getTedarikciler();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTedarikciler", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getTedarikcilerAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTedarikciArama", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getTedarikciArama(string tedarikciAdi, string tedarikciTel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTedarikciArama", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getTedarikciAramaAsync(string tedarikciAdi, string tedarikciTel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postTedarikciGuncelle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet postTedarikciGuncelle(string tedarikciAdi, string tedarikciAdres, string tedarikciTel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postTedarikciGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> postTedarikciGuncelleAsync(string tedarikciAdi, string tedarikciAdres, string tedarikciTel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postTedarikci", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet postTedarikci(string tedarikciAdi, string tedarikciAdres, string tedarikciTel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/postTedarikci", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> postTedarikciAsync(string tedarikciAdi, string tedarikciAdres, string tedarikciTel);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : MarketStokOtomasyonu.MarketStokWebServis.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<MarketStokOtomasyonu.MarketStokWebServis.WebService1Soap>, MarketStokOtomasyonu.MarketStokWebServis.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getUrunler() {
            return base.Channel.getUrunler();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getUrunlerAsync() {
            return base.Channel.getUrunlerAsync();
        }
        
        public System.Data.DataSet getStokBiten() {
            return base.Channel.getStokBiten();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getStokBitenAsync() {
            return base.Channel.getStokBitenAsync();
        }
        
        public System.Data.DataSet getStokAzalan() {
            return base.Channel.getStokAzalan();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getStokAzalanAsync() {
            return base.Channel.getStokAzalanAsync();
        }
        
        public System.Data.DataSet getKategori() {
            return base.Channel.getKategori();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getKategoriAsync() {
            return base.Channel.getKategoriAsync();
        }
        
        public System.Data.DataSet postUrunSil(string barkod) {
            return base.Channel.postUrunSil(barkod);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> postUrunSilAsync(string barkod) {
            return base.Channel.postUrunSilAsync(barkod);
        }
        
        public System.Data.DataSet postUrun(string urun_barkod, int kategori_id, string urun_adi, int miktar, string fiyat) {
            return base.Channel.postUrun(urun_barkod, kategori_id, urun_adi, miktar, fiyat);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> postUrunAsync(string urun_barkod, int kategori_id, string urun_adi, int miktar, string fiyat) {
            return base.Channel.postUrunAsync(urun_barkod, kategori_id, urun_adi, miktar, fiyat);
        }
        
        public System.Data.DataSet postUrunGuncelle(string urun_barkod, int kategori_id, string urun_adi, int miktar, string fiyat) {
            return base.Channel.postUrunGuncelle(urun_barkod, kategori_id, urun_adi, miktar, fiyat);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> postUrunGuncelleAsync(string urun_barkod, int kategori_id, string urun_adi, int miktar, string fiyat) {
            return base.Channel.postUrunGuncelleAsync(urun_barkod, kategori_id, urun_adi, miktar, fiyat);
        }
        
        public System.Data.DataSet getArama(string barkod, string urun_adi, string kategori_adi) {
            return base.Channel.getArama(barkod, urun_adi, kategori_adi);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAramaAsync(string barkod, string urun_adi, string kategori_adi) {
            return base.Channel.getAramaAsync(barkod, urun_adi, kategori_adi);
        }
        
        public System.Data.DataSet SorguCalistir(string query) {
            return base.Channel.SorguCalistir(query);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SorguCalistirAsync(string query) {
            return base.Channel.SorguCalistirAsync(query);
        }
        
        public System.Data.DataSet getTedarikciler() {
            return base.Channel.getTedarikciler();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getTedarikcilerAsync() {
            return base.Channel.getTedarikcilerAsync();
        }
        
        public System.Data.DataSet getTedarikciArama(string tedarikciAdi, string tedarikciTel) {
            return base.Channel.getTedarikciArama(tedarikciAdi, tedarikciTel);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getTedarikciAramaAsync(string tedarikciAdi, string tedarikciTel) {
            return base.Channel.getTedarikciAramaAsync(tedarikciAdi, tedarikciTel);
        }
        
        public System.Data.DataSet postTedarikciGuncelle(string tedarikciAdi, string tedarikciAdres, string tedarikciTel) {
            return base.Channel.postTedarikciGuncelle(tedarikciAdi, tedarikciAdres, tedarikciTel);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> postTedarikciGuncelleAsync(string tedarikciAdi, string tedarikciAdres, string tedarikciTel) {
            return base.Channel.postTedarikciGuncelleAsync(tedarikciAdi, tedarikciAdres, tedarikciTel);
        }
        
        public System.Data.DataSet postTedarikci(string tedarikciAdi, string tedarikciAdres, string tedarikciTel) {
            return base.Channel.postTedarikci(tedarikciAdi, tedarikciAdres, tedarikciTel);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> postTedarikciAsync(string tedarikciAdi, string tedarikciAdres, string tedarikciTel) {
            return base.Channel.postTedarikciAsync(tedarikciAdi, tedarikciAdres, tedarikciTel);
        }
    }
}
